#项目启动端口
server:
  port: 8081
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appschool?characterEncoding=UTF8&autoReconnect=true&useSSL=true
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#sql语句日志打印
logging:
  level:
    com:
      mashibing:
        mapper: debug